using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PubSubLib.Mirror.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class MirrorProtoGenerator : IIncrementalGenerator
{
    private const string MirrorProtoAttr = "PubSubLib.Mirror.MirrorProtoAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider.ForAttributeWithMetadataName(
            MirrorProtoAttr,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => TransformClass(ctx)
        );

        var valid = classes.Where(static c => c is not null);

        context.RegisterSourceOutput(valid, static (spc, info) => GenerateCode(spc, info!.Value));
    }

    private static MirrorClassInfo? TransformClass(GeneratorAttributeSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.TargetNode;
        var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        if (!classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            return null;

        var attr = ctx.Attributes[0];
        if (attr.ConstructorArguments.Length < 1 || attr.ConstructorArguments[0].Value is not INamedTypeSymbol protoType)
            return null;

        string? dataName = null;
        foreach (var namedArg in attr.NamedArguments)
        {
            if (namedArg.Key == "DataName" && namedArg.Value.Value is string dn)
                dataName = dn;
        }
        dataName ??= protoType.Name;

        var ns = classSymbol.ContainingNamespace?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .TrimStartGlobalPrefix() ?? "";

        var fields = new List<FieldMapping>();
        var reserved = new HashSet<string> { "PlayerId", "IsOnLine", "DataName" };

        foreach (var member in protoType.GetMembers())
        {
            if (member is not IPropertySymbol propSymbol) continue;
            if (propSymbol.IsStatic) continue;
            if (propSymbol.IsIndexer) continue;
            if (!propSymbol.ExplicitInterfaceImplementations.IsEmpty) continue;
            if (!SymbolEqualityComparer.Default.Equals(propSymbol.ContainingType, protoType)) continue;

            var propName = propSymbol.Name;
            if (reserved.Contains(propName)) continue;
            if (propName.EndsWith("Case") && propSymbol.Type.TypeKind == TypeKind.Enum) continue;

            var fieldName = ToFieldName(propName);
            var typeName = propSymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .TrimStartGlobalPrefix();

            fields.Add(new FieldMapping(fieldName, propName, typeName));
        }

        var fullProtoName = protoType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .TrimStartGlobalPrefix();

        return new MirrorClassInfo(ns, classSymbol.Name, fullProtoName, dataName, fields.ToArray());
    }

    private static string ToFieldName(string propertyName)
    {
        if (string.IsNullOrEmpty(propertyName)) return "_";
        return "_" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);
    }

    private static void GenerateCode(SourceProductionContext context, MirrorClassInfo info)
    {
        if (info.Fields.Length == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Google.Protobuf;");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8618");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }
        sb.AppendLine($"partial class {info.ClassName} : global::PubSubLib.IPlayerData, global::PubSubLib.IPlayerDataInternal");
        sb.AppendLine("{");
        sb.AppendLine($"    private {info.ProtoTypeFullName}? _mirrorProto;");
        sb.AppendLine("    private Action<byte[], string>? _onChange;");
        sb.AppendLine();
        sb.AppendLine("    private long ___gs_playerId;");
        sb.AppendLine("    public long PlayerId => ___gs_playerId;");
        sb.AppendLine("    void global::PubSubLib.IPlayerDataInternal.SetPlayerId(long playerId) => ___gs_playerId = playerId;");
        sb.AppendLine();
        sb.AppendLine("    private bool ___gs_isOnLine;");
        sb.AppendLine("    public bool IsOnLine => ___gs_isOnLine;");
        sb.AppendLine("    void global::PubSubLib.IPlayerDataInternal.SetOnline(bool isOnline) => ___gs_isOnLine = isOnline;");
        sb.AppendLine();
        sb.AppendLine($"    public string DataName => \"{info.DataName}\";");
        sb.AppendLine();
        sb.AppendLine($"    public {info.ProtoTypeFullName} GetMirrorProto()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_mirrorProto is null)");
        sb.AppendLine($"            _mirrorProto = new {info.ProtoTypeFullName}();");
        sb.AppendLine("        return _mirrorProto;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void OnChange(Action<byte[], string> handler)");
        sb.AppendLine("    {");
        sb.AppendLine("        _onChange += handler;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private void Notify(byte[] bytes, string commit)");
        sb.AppendLine("    {");
        sb.AppendLine("        _onChange?.Invoke(bytes, commit);");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var f in info.Fields)
        {
            sb.AppendLine($"    private {f.TypeName} {f.FieldName};");
            sb.AppendLine();
            sb.AppendLine($"    public {f.TypeName} {f.PropertyName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        get => {f.FieldName};");
            sb.AppendLine($"        set => {f.FieldName} = value;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    public void Commit(string commit)");
        sb.AppendLine("    {");
        sb.AppendLine("        var proto = GetMirrorProto();");
        foreach (var f in info.Fields)
            sb.AppendLine($"        proto.{f.PropertyName} = {f.FieldName};");
        sb.AppendLine("        Notify(proto.ToByteArray(), commit);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void SyncFromProto()");
        sb.AppendLine("    {");
        sb.AppendLine("        var proto = GetMirrorProto();");
        foreach (var f in info.Fields)
            sb.AppendLine($"        {f.FieldName} = proto.{f.PropertyName};");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        if (!string.IsNullOrEmpty(info.Namespace))
            sb.AppendLine("}");

        context.AddSource($"{info.ClassName}.g.cs", sb.ToString());
    }
}

internal static class StringExtensions
{
    public static string TrimStartGlobalPrefix(this string s)
    {
        const string prefix = "global::";
        if (s.StartsWith(prefix))
            return s.Substring(prefix.Length);
        return s;
    }
}

internal readonly struct FieldMapping
{
    public readonly string FieldName;
    public readonly string PropertyName;
    public readonly string TypeName;
    public FieldMapping(string fieldName, string propertyName, string typeName)
    {
        FieldName = fieldName;
        PropertyName = propertyName;
        TypeName = typeName;
    }
}

internal readonly struct MirrorClassInfo
{
    public readonly string Namespace;
    public readonly string ClassName;
    public readonly string ProtoTypeFullName;
    public readonly string DataName;
    public readonly FieldMapping[] Fields;
    public MirrorClassInfo(string ns, string className, string protoTypeFullName, string dataName, FieldMapping[] fields)
    {
        Namespace = ns;
        ClassName = className;
        ProtoTypeFullName = protoTypeFullName;
        DataName = dataName;
        Fields = fields;
    }
}
