using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PubSubLib.Mirror.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class MirrorProtoClientGenerator : IIncrementalGenerator
{
    private const string AttrName = "PubSubLib.Mirror.MirrorProtoClientAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttrName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => TransformClass(ctx)
        );

        var valid = classes.Where(static c => c is not null);

        context.RegisterSourceOutput(valid, static (spc, info) => GenerateCode(spc, info!.Value));
    }

    private static MirrorClassInfo? TransformClass(GeneratorAttributeSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.TargetNode;
        var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        if (!classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            return null;

        var attr = ctx.Attributes[0];
        if (attr.ConstructorArguments.Length < 1 || attr.ConstructorArguments[0].Value is not INamedTypeSymbol protoType)
            return null;

        var dataName = protoType.Name;

        var ns = classSymbol.ContainingNamespace?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .TrimStartGlobalPrefix() ?? "";

        var fields = new List<FieldMapping>();
        var reserved = new HashSet<string> { "PlayerId", "IsOnLine", "DataName" };

        foreach (var member in protoType.GetMembers())
        {
            if (member is not IPropertySymbol propSymbol) continue;
            if (propSymbol.IsStatic) continue;
            if (propSymbol.IsIndexer) continue;
            if (!propSymbol.ExplicitInterfaceImplementations.IsEmpty) continue;
            if (!SymbolEqualityComparer.Default.Equals(propSymbol.ContainingType, protoType)) continue;

            var propName = propSymbol.Name;
            if (reserved.Contains(propName)) continue;
            if (propName.EndsWith("Case") && propSymbol.Type.TypeKind == TypeKind.Enum) continue;

            var fieldName = ToFieldName(propName);
            var typeName = propSymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .TrimStartGlobalPrefix();

            var isRepeated = false;
            var elementTypeName = typeName;
            if (propSymbol.Type is INamedTypeSymbol namedType && namedType.IsGenericType
                && namedType.MetadataName == "RepeatedField`1"
                && namedType.ContainingNamespace?.ToDisplayString() == "Google.Protobuf.Collections")
            {
                isRepeated = true;
                elementTypeName = namedType.TypeArguments[0]
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    .TrimStartGlobalPrefix();
            }

            fields.Add(new FieldMapping(fieldName, propName, typeName, isRepeated, elementTypeName, !propSymbol.Type.IsValueType));
        }

        var (structGroups, structGroupIndex) = MirrorProtoGenerator.DetectStructGroups(fields);
        for (int i = 0; i < fields.Count; i++)
        {
            if (structGroupIndex[i] >= 0)
            {
                var f = fields[i];
                fields[i] = new FieldMapping(f.FieldName, f.PropertyName, f.TypeName, f.IsRepeated, f.ElementTypeName, f.IsReferenceType, structGroupIndex[i]);
            }
        }

        var fullProtoName = protoType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .TrimStartGlobalPrefix();

        return new MirrorClassInfo(ns, classSymbol.Name, fullProtoName, dataName, fields.ToArray(), structGroups);
    }

    private static string ToFieldName(string propertyName)
    {
        if (string.IsNullOrEmpty(propertyName)) return "_";
        return "_" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);
    }

    private static void GenerateCode(SourceProductionContext context, MirrorClassInfo info)
    {
        if (info.Fields.Length == 0 && info.StructGroups.Length == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8618");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }
        sb.AppendLine($"partial class {info.ClassName} : global::PubSubLib.Mirror.IPlayerMirrorClient");
        sb.AppendLine("{");

        foreach (var sg in info.StructGroups)
        {
            sb.AppendLine();
            sb.AppendLine($"    public struct {sg.StructName}");
            sb.AppendLine("    {");
            for (int i = 0; i < sg.FieldPropNames.Length; i++)
            {
                sb.AppendLine($"        public {sg.ElementTypes[i]} {sg.FieldPropNames[i]} {{ get; }}");
            }
            sb.AppendLine();
            var ctorArgs = new List<string>();
            for (int i = 0; i < sg.FieldPropNames.Length; i++)
            {
                ctorArgs.Add($"{sg.ElementTypes[i]} {char.ToLowerInvariant(sg.FieldPropNames[i][0])}{sg.FieldPropNames[i].Substring(1)}");
            }
            sb.AppendLine($"        public {sg.StructName}({string.Join(", ", ctorArgs)})");
            sb.AppendLine("        {");
            for (int i = 0; i < sg.FieldPropNames.Length; i++)
            {
                var argName = $"{char.ToLowerInvariant(sg.FieldPropNames[i][0])}{sg.FieldPropNames[i].Substring(1)}";
                sb.AppendLine($"            {sg.FieldPropNames[i]} = {argName};");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        sb.AppendLine($"    private {info.ProtoTypeFullName}? _mirrorProto;");
        sb.AppendLine();
        sb.AppendLine("    private long ___gs_playerId;");
        sb.AppendLine("    public long PlayerId { get => ___gs_playerId; set => ___gs_playerId = value; }");
        sb.AppendLine();
        sb.AppendLine($"    public string DataName => \"{info.DataName}\";");
        sb.AppendLine();
        sb.AppendLine($"    public {info.ProtoTypeFullName} GetMirrorProto()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_mirrorProto is null)");
        sb.AppendLine($"            _mirrorProto = new {info.ProtoTypeFullName}();");
        sb.AppendLine("        return _mirrorProto;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    partial void OnCommit(string commit);");
        sb.AppendLine();

        foreach (var f in info.Fields)
        {
            if (f.StructGroupIndex >= 0) continue;

            if (f.IsRepeated)
            {
                var fieldType = $"System.Collections.Generic.List<{f.ElementTypeName}>";
                var propType = $"System.Collections.Generic.IReadOnlyList<{f.ElementTypeName}>";
                sb.AppendLine($"    private readonly {fieldType} {f.FieldName} = new();");
                sb.AppendLine();
                sb.AppendLine($"    public {propType} {f.PropertyName} => {f.FieldName};");
            }
            else
            {
                sb.AppendLine($"    private {f.TypeName} {f.FieldName};");
                sb.AppendLine();
                sb.AppendLine($"    public {f.TypeName} {f.PropertyName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        get => {f.FieldName};");
                sb.AppendLine("    }");
            }
            sb.AppendLine();
        }

        foreach (var sg in info.StructGroups)
        {
            var fieldType = $"System.Collections.Generic.List<{sg.StructName}>";
            var propType = $"System.Collections.Generic.IReadOnlyList<{sg.StructName}>";
            sb.AppendLine($"    private readonly {fieldType} {sg.FieldName} = new();");
            sb.AppendLine();
            sb.AppendLine($"    public {propType} {sg.StructName}s => {sg.FieldName};");
            sb.AppendLine();
        }

        sb.AppendLine("    public void SyncFromProto()");
        sb.AppendLine("    {");
        sb.AppendLine("        var proto = GetMirrorProto();");
        foreach (var sg in info.StructGroups)
        {
            sb.AppendLine($"        {sg.FieldName}.Clear();");
            sb.AppendLine($"        int __count = proto.{sg.ProtoPropNames[0]}.Count;");
            sb.AppendLine("        for (int __i = 0; __i < __count; __i++)");
            sb.AppendLine("        {");
            var ctorArgs = new List<string>();
            for (int i = 0; i < sg.ProtoPropNames.Length; i++)
            {
                if (sg.IsRefTypes[i])
                {
                    ctorArgs.Add($"__i < proto.{sg.ProtoPropNames[i]}.Count ? proto.{sg.ProtoPropNames[i]}[__i] : default");
                }
                else
                {
                    ctorArgs.Add($"__i < proto.{sg.ProtoPropNames[i]}.Count ? proto.{sg.ProtoPropNames[i]}[__i] : default");
                }
            }
            sb.AppendLine($"            {sg.FieldName}.Add(new {sg.StructName}({string.Join(", ", ctorArgs)}));");
            sb.AppendLine("        }");
        }
        foreach (var f in info.Fields)
        {
            if (f.StructGroupIndex >= 0) continue;
            if (f.IsRepeated)
            {
                sb.AppendLine($"        {f.FieldName}.Clear();");
                sb.AppendLine($"        {f.FieldName}.AddRange(proto.{f.PropertyName});");
            }
            else
            {
                sb.AppendLine($"        {f.FieldName} = proto.{f.PropertyName};");
            }
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void ApplyUpdate(byte[] data, string commit)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var proto = {info.ProtoTypeFullName}.Parser.ParseFrom(data);");
        sb.AppendLine("        _mirrorProto = proto;");
        sb.AppendLine("        SyncFromProto();");
        sb.AppendLine("        OnCommit(commit);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        if (!string.IsNullOrEmpty(info.Namespace))
            sb.AppendLine("}");

        context.AddSource($"{info.ClassName}.g.cs", sb.ToString());
    }
}
