using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PubSubLib.Mirror.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class MirrorProtoClientGenerator : IIncrementalGenerator
{
    private const string AttrName = "PubSubLib.Mirror.MirrorProtoClientAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttrName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => TransformClass(ctx)
        );

        var valid = classes.Where(static c => c is not null);

        context.RegisterSourceOutput(valid, static (spc, info) => GenerateCode(spc, info!.Value));
    }

    private static MirrorClassInfo? TransformClass(GeneratorAttributeSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.TargetNode;
        var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        if (!classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            return null;

        var attr = ctx.Attributes[0];
        if (attr.ConstructorArguments.Length < 1 || attr.ConstructorArguments[0].Value is not INamedTypeSymbol protoType)
            return null;

        var dataName = protoType.Name;

        var ns = classSymbol.ContainingNamespace?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .TrimStartGlobalPrefix() ?? "";

        var fields = new List<FieldMapping>();
        var reserved = new HashSet<string> { "PlayerId", "IsOnLine", "DataName" };

        foreach (var member in protoType.GetMembers())
        {
            if (member is not IPropertySymbol propSymbol) continue;
            if (propSymbol.IsStatic) continue;
            if (propSymbol.IsIndexer) continue;
            if (!propSymbol.ExplicitInterfaceImplementations.IsEmpty) continue;
            if (!SymbolEqualityComparer.Default.Equals(propSymbol.ContainingType, protoType)) continue;

            var propName = propSymbol.Name;
            if (reserved.Contains(propName)) continue;
            if (propName.EndsWith("Case") && propSymbol.Type.TypeKind == TypeKind.Enum) continue;

            var fieldName = ToFieldName(propName);
            var typeName = propSymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .TrimStartGlobalPrefix();

            fields.Add(new FieldMapping(fieldName, propName, typeName));
        }

        var fullProtoName = protoType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .TrimStartGlobalPrefix();

        return new MirrorClassInfo(ns, classSymbol.Name, fullProtoName, dataName, fields.ToArray());
    }

    private static string ToFieldName(string propertyName)
    {
        if (string.IsNullOrEmpty(propertyName)) return "_";
        return "_" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);
    }

    private static void GenerateCode(SourceProductionContext context, MirrorClassInfo info)
    {
        if (info.Fields.Length == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8618");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }
        sb.AppendLine($"partial class {info.ClassName} : global::PubSubLib.Mirror.IPlayerMirrorClient");
        sb.AppendLine("{");
        sb.AppendLine($"    private {info.ProtoTypeFullName}? _mirrorProto;");
        sb.AppendLine();
        sb.AppendLine("    private long ___gs_playerId;");
        sb.AppendLine("    public long PlayerId { get => ___gs_playerId; set => ___gs_playerId = value; }");
        sb.AppendLine();
        sb.AppendLine($"    public string DataName => \"{info.DataName}\";");
        sb.AppendLine();
        sb.AppendLine($"    public {info.ProtoTypeFullName} GetMirrorProto()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_mirrorProto is null)");
        sb.AppendLine($"            _mirrorProto = new {info.ProtoTypeFullName}();");
        sb.AppendLine("        return _mirrorProto;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    partial void OnCommit(string commit);");
        sb.AppendLine();

        foreach (var f in info.Fields)
        {
            sb.AppendLine($"    private {f.TypeName} {f.FieldName};");
            sb.AppendLine();
            sb.AppendLine($"    public {f.TypeName} {f.PropertyName}");
            sb.AppendLine("    {");
            sb.AppendLine($"        get => {f.FieldName};");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    public void SyncFromProto()");
        sb.AppendLine("    {");
        sb.AppendLine("        var proto = GetMirrorProto();");
        foreach (var f in info.Fields)
            sb.AppendLine($"        {f.FieldName} = proto.{f.PropertyName};");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void ApplyUpdate(byte[] data, string commit)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var proto = {info.ProtoTypeFullName}.Parser.ParseFrom(data);");
        sb.AppendLine("        _mirrorProto = proto;");
        sb.AppendLine("        SyncFromProto();");
        sb.AppendLine("        OnCommit(commit);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        if (!string.IsNullOrEmpty(info.Namespace))
            sb.AppendLine("}");

        context.AddSource($"{info.ClassName}.g.cs", sb.ToString());
    }
}
