using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PubSubLib.Mirror.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class UnitMirrorGenerator : IIncrementalGenerator
{
    private const string AttrName = "PubSubLib.Mirror.UnitMirrorServerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttrName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => TransformClass(ctx)
        );

        var valid = classes.Where(static c => c is not null);

        context.RegisterSourceOutput(valid, static (spc, info) => GenerateCode(spc, info!.Value));
    }

    private static UnitMirrorClassInfo? TransformClass(GeneratorAttributeSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.TargetNode;
        var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        if (!classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            return null;

        var attr = ctx.Attributes[0];
        if (attr.ConstructorArguments.Length < 1 || attr.ConstructorArguments[0].Value is not INamedTypeSymbol protoType)
            return null;

        string? unitType = null;
        foreach (var namedArg in attr.NamedArguments)
        {
            if (namedArg.Key == "UnitType" && namedArg.Value.Value is string ut)
                unitType = ut;
        }
        unitType ??= protoType.Name;

        var ns = classSymbol.ContainingNamespace?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .TrimStartGlobalPrefix() ?? "";

        var fields = new List<FieldMapping>();
        var reserved = new HashSet<string> { "PlayerId", "IsOnLine", "DataName" };

        foreach (var member in protoType.GetMembers())
        {
            if (member is not IPropertySymbol propSymbol) continue;
            if (propSymbol.IsStatic) continue;
            if (propSymbol.IsIndexer) continue;
            if (!propSymbol.ExplicitInterfaceImplementations.IsEmpty) continue;
            if (!SymbolEqualityComparer.Default.Equals(propSymbol.ContainingType, protoType)) continue;

            var propName = propSymbol.Name;
            if (reserved.Contains(propName)) continue;
            if (propName.EndsWith("Case") && propSymbol.Type.TypeKind == TypeKind.Enum) continue;

            var fieldName = ToFieldName(propName);
            var typeName = propSymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .TrimStartGlobalPrefix();

            var isRepeated = false;
            var elementTypeName = typeName;
            if (propSymbol.Type is INamedTypeSymbol namedType && namedType.IsGenericType
                && namedType.MetadataName == "RepeatedField`1"
                && namedType.ContainingNamespace?.ToDisplayString() == "Google.Protobuf.Collections")
            {
                isRepeated = true;
                elementTypeName = namedType.TypeArguments[0]
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    .TrimStartGlobalPrefix();
            }

            fields.Add(new FieldMapping(fieldName, propName, typeName, isRepeated, elementTypeName, !propSymbol.Type.IsValueType));
        }

        var fullProtoName = protoType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .TrimStartGlobalPrefix();

        var (structGroups, structGroupIndex) = MirrorProtoGenerator.DetectStructGroups(fields);
        for (int i = 0; i < fields.Count; i++)
        {
            if (structGroupIndex[i] >= 0)
            {
                var f = fields[i];
                fields[i] = new FieldMapping(f.FieldName, f.PropertyName, f.TypeName, f.IsRepeated, f.ElementTypeName, f.IsReferenceType, structGroupIndex[i]);
            }
        }

        return new UnitMirrorClassInfo(ns, classSymbol.Name, fullProtoName, unitType, null, fields.ToArray(), structGroups);
    }

    private static string ToFieldName(string propertyName)
    {
        if (string.IsNullOrEmpty(propertyName)) return "_";
        return "_" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);
    }

    private static void GenerateCode(SourceProductionContext context, UnitMirrorClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Google.Protobuf;");
        sb.AppendLine("using PubSubLib;");
        sb.AppendLine("using PubSubLib.Contracts;");
        sb.AppendLine("using PubSubLib.Messages;");
        sb.AppendLine("using PubSubLib.Mirror;");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8618");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }
        sb.AppendLine($"partial class {info.ClassName} : global::PubSubLib.IRegionUnit<{info.ProtoTypeFullName}>, global::PubSubLib.IRegionUnitInternal");
        sb.AppendLine("{");

        sb.AppendLine($"    public static string _unitType = \"{info.UnitType}\";");
        sb.AppendLine($"    public string UnitType => _unitType;");
        sb.AppendLine();
        sb.AppendLine("    private global::PubSubLib.IUnit _unit;");
        sb.AppendLine();
        sb.AppendLine("    void global::PubSubLib.IRegionUnitInternal.SetUnit(global::PubSubLib.IUnit unit) => _unit = unit;");
        sb.AppendLine("    string global::PubSubLib.IRegionUnitInternal.GetUnitType() => _unitType;");
        sb.AppendLine("    global::PubSubLib.IUnit global::PubSubLib.IRegionUnitInternal.GetUnit() => _unit;");
        sb.AppendLine();
        sb.AppendLine("    public long Id => _unit.Id;");
        sb.AppendLine();
        sb.AppendLine("    public global::PubSubLib.Vector2 Position");
        sb.AppendLine("    {");
        sb.AppendLine("        get => _unit.Position;");
        sb.AppendLine("        set => _unit.Position = value;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public {info.ProtoTypeFullName} Get()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_unit.Data == null || _unit.Data.Length == 0)");
        sb.AppendLine($"            return new {info.ProtoTypeFullName}();");
        sb.AppendLine($"        return {info.ProtoTypeFullName}.Parser.ParseFrom(_unit.Data);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void SetPosition(float x, float y)");
        sb.AppendLine("    {");
        sb.AppendLine("        _unit.Position = new global::PubSubLib.Vector2 { x = x, y = y };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void SetPosition(global::PubSubLib.Vector2 position)");
        sb.AppendLine("    {");
        sb.AppendLine("        _unit.Position = position;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void Destroy()");
        sb.AppendLine("    {");
        sb.AppendLine("        _unit.Destroy();");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    private {info.ProtoTypeFullName}? _mirrorProto;");
        sb.AppendLine($"    public {info.ProtoTypeFullName} GetMirrorProto()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_mirrorProto is null)");
        sb.AppendLine($"            _mirrorProto = new {info.ProtoTypeFullName}();");
        sb.AppendLine("        return _mirrorProto;");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var f in info.Fields)
        {
            if (f.StructGroupIndex >= 0) continue;
            if (f.IsRepeated)
            {
                var listType = $"global::PubSubLib.Mirror.MirrorRepeatedList<{f.ElementTypeName}>";
                sb.AppendLine($"    private readonly {listType} {f.FieldName} = new();");
                sb.AppendLine();
                sb.AppendLine($"    public {listType} {f.PropertyName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        get => {f.FieldName};");
                sb.AppendLine("    }");
            }
            else
            {
                sb.AppendLine($"    private {f.TypeName} {f.FieldName};");
                sb.AppendLine();
                sb.AppendLine($"    public {f.TypeName} {f.PropertyName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        get => {f.FieldName};");
                sb.AppendLine($"        set => {f.FieldName} = value;");
                sb.AppendLine("    }");
            }
            sb.AppendLine();
        }

        if (info.Fields.Any(f => f.StructGroupIndex < 0))
        {
            sb.AppendLine("    public void Commit(string commit)");
            sb.AppendLine("    {");
            sb.AppendLine("        var proto = GetMirrorProto();");
            foreach (var f in info.Fields)
            {
                if (f.StructGroupIndex >= 0) continue;
                if (f.IsRepeated)
                    sb.AppendLine($"        {f.ElementTypeName}[]? ___arr_{f.FieldName} = {f.FieldName}.TrySnapshot();");
            }
            sb.AppendLine("        MirrorProtoBus.Enqueue(proto,");
            sb.AppendLine("            __bytes =>");
            sb.AppendLine("            {");
            sb.AppendLine("                _unit.Data = __bytes;");
            sb.AppendLine("                var __commit = new RegionCommit { Commit = commit, MirrorData = Google.Protobuf.ByteString.CopyFrom(__bytes) };");
            sb.AppendLine("                _unit.PublishEvent(\"commit\", __commit.ToByteArray(), true);");
            sb.AppendLine("            },");
            sb.AppendLine("            __p =>");
            sb.AppendLine("            {");
            foreach (var f in info.Fields)
            {
                if (f.StructGroupIndex >= 0) continue;
                if (f.IsRepeated)
                {
                    sb.AppendLine($"                if (___arr_{f.FieldName} is not null)");
                    sb.AppendLine("                {");
                    sb.AppendLine($"                    __p.{f.PropertyName}.Clear();");
                    sb.AppendLine($"                    __p.{f.PropertyName}.AddRange(___arr_{f.FieldName});");
                    sb.AppendLine("                }");
                }
                else if (f.IsReferenceType)
                {
                    sb.AppendLine($"                if ({f.FieldName} is not null) __p.{f.PropertyName} = {f.FieldName};");
                }
                else
                {
                    sb.AppendLine($"                __p.{f.PropertyName} = {f.FieldName};");
                }
            }
            sb.AppendLine("            });");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    public void SendMessage<TProto>(string subject, TProto message, bool reliable)");
        sb.AppendLine("        where TProto : class, global::Google.Protobuf.IMessage<TProto>, new()");
        sb.AppendLine("    {");
        sb.AppendLine("        MirrorProtoBus.EnqueueMessage(subject, message,");
        sb.AppendLine("            (__subject, __bytes) =>");
        sb.AppendLine("            {");
        sb.AppendLine("                var __rmsg = new RegionMessage { Subject = __subject, Data = Google.Protobuf.ByteString.CopyFrom(__bytes) };");
        sb.AppendLine("                _unit.PublishEvent(\"message\", __rmsg.ToByteArray(), reliable);");
        sb.AppendLine("            });");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        if (!string.IsNullOrEmpty(info.Namespace))
            sb.AppendLine("}");

        context.AddSource($"{info.ClassName}.UnitMirror.g.cs", sb.ToString());
    }
}

internal readonly struct UnitMirrorClassInfo
{
    public readonly string Namespace;
    public readonly string ClassName;
    public readonly string ProtoTypeFullName;
    public readonly string UnitType;
    public readonly string? TargetTypeFullName;
    public readonly FieldMapping[] Fields;
    public readonly StructGroup[] StructGroups;
    public UnitMirrorClassInfo(string ns, string className, string protoTypeFullName, string unitType, string? targetTypeFullName, FieldMapping[] fields, StructGroup[] structGroups)
    {
        Namespace = ns;
        ClassName = className;
        ProtoTypeFullName = protoTypeFullName;
        UnitType = unitType;
        TargetTypeFullName = targetTypeFullName;
        Fields = fields;
        StructGroups = structGroups;
    }
}
