using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PubSubLib.Mirror.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class UnitMirrorClientGenerator : IIncrementalGenerator
{
    private const string AttrName = "PubSubLib.Mirror.UnitMirrorClientAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classes = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttrName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, _) => TransformClass(ctx)
        );

        var valid = classes.Where(static c => c is not null);

        context.RegisterSourceOutput(valid, static (spc, info) => GenerateCode(spc, info!.Value));
    }

    private static UnitMirrorClassInfo? TransformClass(GeneratorAttributeSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.TargetNode;
        var classSymbol = (INamedTypeSymbol)ctx.TargetSymbol;

        if (!classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            return null;

        var attr = ctx.Attributes[0];
        if (attr.ConstructorArguments.Length < 1 || attr.ConstructorArguments[0].Value is not INamedTypeSymbol protoType)
            return null;

        string? unitType = null;
        foreach (var namedArg in attr.NamedArguments)
        {
            if (namedArg.Key == "UnitType" && namedArg.Value.Value is string ut)
                unitType = ut;
        }
        unitType ??= protoType.Name;

        var ns = classSymbol.ContainingNamespace?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .TrimStartGlobalPrefix() ?? "";

        var fields = new List<FieldMapping>();
        var reserved = new HashSet<string> { "PlayerId", "IsOnLine", "DataName" };

        foreach (var member in protoType.GetMembers())
        {
            if (member is not IPropertySymbol propSymbol) continue;
            if (propSymbol.IsStatic) continue;
            if (propSymbol.IsIndexer) continue;
            if (!propSymbol.ExplicitInterfaceImplementations.IsEmpty) continue;
            if (!SymbolEqualityComparer.Default.Equals(propSymbol.ContainingType, protoType)) continue;

            var propName = propSymbol.Name;
            if (reserved.Contains(propName)) continue;
            if (propName.EndsWith("Case") && propSymbol.Type.TypeKind == TypeKind.Enum) continue;

            var fieldName = ToFieldName(propName);
            var typeName = propSymbol.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                .TrimStartGlobalPrefix();

            var isRepeated = false;
            var elementTypeName = typeName;
            if (propSymbol.Type is INamedTypeSymbol namedType && namedType.IsGenericType
                && namedType.MetadataName == "RepeatedField`1"
                && namedType.ContainingNamespace?.ToDisplayString() == "Google.Protobuf.Collections")
            {
                isRepeated = true;
                elementTypeName = namedType.TypeArguments[0]
                    .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    .TrimStartGlobalPrefix();
            }

            fields.Add(new FieldMapping(fieldName, propName, typeName, isRepeated, elementTypeName, !propSymbol.Type.IsValueType));
        }

        var fullProtoName = protoType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .TrimStartGlobalPrefix();

        var (structGroups, structGroupIndex) = MirrorProtoGenerator.DetectStructGroups(fields);
        for (int i = 0; i < fields.Count; i++)
        {
            if (structGroupIndex[i] >= 0)
            {
                var f = fields[i];
                fields[i] = new FieldMapping(f.FieldName, f.PropertyName, f.TypeName, f.IsRepeated, f.ElementTypeName, f.IsReferenceType, structGroupIndex[i]);
            }
        }

        return new UnitMirrorClassInfo(ns, classSymbol.Name, fullProtoName, unitType, fields.ToArray(), structGroups);
    }

    private static string ToFieldName(string propertyName)
    {
        if (string.IsNullOrEmpty(propertyName)) return "_";
        return "_" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1);
    }

    private static void GenerateCode(SourceProductionContext context, UnitMirrorClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Google.Protobuf;");
        sb.AppendLine("using PubSubLib;");
        sb.AppendLine("using PubSubLib.Client;");
        sb.AppendLine("using PubSubLib.Contracts;");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8618");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(info.Namespace))
        {
            sb.AppendLine($"namespace {info.Namespace}");
            sb.AppendLine("{");
        }
        sb.AppendLine($"partial class {info.ClassName} : global::PubSubLib.Client.IRegionClientUnitInternal");
        sb.AppendLine("{");

        sb.AppendLine($"    public static string _unitType = \"{info.UnitType}\";");
        sb.AppendLine($"    public string UnitType => _unitType;");
        sb.AppendLine();
        sb.AppendLine("    private long _id;");
        sb.AppendLine("    private global::PubSubLib.Vector2 _position;");
        sb.AppendLine("    private global::PubSubLib.Client.IAlive _target;");
        sb.AppendLine();
        sb.AppendLine("    public long Id => _id;");
        sb.AppendLine();
        sb.AppendLine("    void global::PubSubLib.Client.IRegionClientUnitInternal.Init(long id, global::PubSubLib.Vector2 position)");
        sb.AppendLine("    {");
        sb.AppendLine("        _id = id;");
        sb.AppendLine("        _position = position;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    long global::PubSubLib.Client.IRegionClientUnitInternal.GetId() => _id;");
        sb.AppendLine();
        sb.AppendLine("    void global::PubSubLib.Client.IRegionClientUnitInternal.SetTarget(global::PubSubLib.Client.IAlive target) => _target = target;");
        sb.AppendLine("    string global::PubSubLib.Client.IRegionClientUnitInternal.GetUnitType() => _unitType;");
        sb.AppendLine("    global::PubSubLib.Client.IAlive global::PubSubLib.Client.IRegionClientUnitInternal.GetTarget() => _target;");
        sb.AppendLine();

        sb.AppendLine($"    private {info.ProtoTypeFullName}? _mirrorProto;");
        sb.AppendLine("    private bool _initialized;");
        sb.AppendLine("    public bool IsInitialized => _initialized;");
        sb.AppendLine();
        sb.AppendLine("    partial void OnCommit(string commit);");
        sb.AppendLine("    partial void OnStart();");
        sb.AppendLine();
        sb.AppendLine($"    public {info.ProtoTypeFullName} GetMirrorProto()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_mirrorProto is null)");
        sb.AppendLine($"            _mirrorProto = new {info.ProtoTypeFullName}();");
        sb.AppendLine("        return _mirrorProto;");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var f in info.Fields)
        {
            if (f.StructGroupIndex >= 0) continue;
            if (f.IsRepeated)
            {
                var fieldType = $"System.Collections.Generic.List<{f.ElementTypeName}>";
                var propType = $"System.Collections.Generic.IReadOnlyList<{f.ElementTypeName}>";
                sb.AppendLine($"    private readonly {fieldType} {f.FieldName} = new();");
                sb.AppendLine();
                sb.AppendLine($"    public {propType} {f.PropertyName} => {f.FieldName};");
            }
            else
            {
                sb.AppendLine($"    private {f.TypeName} {f.FieldName};");
                sb.AppendLine();
                sb.AppendLine($"    public {f.TypeName} {f.PropertyName}");
                sb.AppendLine("    {");
                sb.AppendLine($"        get => {f.FieldName};");
                sb.AppendLine("    }");
            }
            sb.AppendLine();
        }

        foreach (var sg in info.StructGroups)
        {
            var fieldType = $"System.Collections.Generic.List<{sg.StructName}>";
            var propType = $"System.Collections.Generic.IReadOnlyList<{sg.StructName}>";
            sb.AppendLine($"    private readonly {fieldType} {sg.FieldName} = new();");
            sb.AppendLine();
            sb.AppendLine($"    public {propType} {sg.StructName}s => {sg.FieldName};");
            sb.AppendLine();
        }

        sb.AppendLine("    public void SyncFromProto()");
        sb.AppendLine("    {");
        sb.AppendLine("        var proto = GetMirrorProto();");
        foreach (var f in info.Fields)
        {
            if (f.StructGroupIndex >= 0) continue;
            if (f.IsRepeated)
            {
                sb.AppendLine($"        {f.FieldName}.Clear();");
                sb.AppendLine($"        {f.FieldName}.AddRange(proto.{f.PropertyName});");
            }
            else
            {
                sb.AppendLine($"        {f.FieldName} = proto.{f.PropertyName};");
            }
        }
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void ApplyUpdate(byte[] mirrorData, string commit)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var proto = {info.ProtoTypeFullName}.Parser.ParseFrom(mirrorData);");
        sb.AppendLine("        _mirrorProto = proto;");
        sb.AppendLine("        SyncFromProto();");
        sb.AppendLine("        if (!_initialized)");
        sb.AppendLine("        {");
        sb.AppendLine("            _initialized = true;");
        sb.AppendLine("            OnStart();");
        sb.AppendLine("        }");
        sb.AppendLine("        OnCommit(commit);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    private readonly Dictionary<string, List<Action<byte[]>>> _msgHandlers = new();");
        sb.AppendLine();
        sb.AppendLine("    public MyConnection.ISubscribe OnMessage<T>(string subject, Action<T> callback)");
        sb.AppendLine("        where T : class, global::Google.Protobuf.IMessage<T>, new()");
        sb.AppendLine("    {");
        sb.AppendLine("        var parser = new global::Google.Protobuf.MessageParser<T>(() => new T());");
        sb.AppendLine("        void handler(byte[] bytes) { callback(parser.ParseFrom(bytes)); }");
        sb.AppendLine("        if (!_msgHandlers.TryGetValue(subject, out var list))");
        sb.AppendLine("            _msgHandlers[subject] = list = new List<Action<byte[]>>();");
        sb.AppendLine("        list.Add(handler);");
        sb.AppendLine("        return new __RegionMsgSub(() => list.Remove(handler));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    void global::PubSubLib.Client.IRegionClientUnitInternal.DispatchMessage(string subject, byte[] data)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_msgHandlers.TryGetValue(subject, out var list))");
        sb.AppendLine("            foreach (var h in list)");
        sb.AppendLine("            {");
        sb.AppendLine("                try { h(data); }");
        sb.AppendLine("                catch (Exception ex) { PubSubLib.Contracts.PubSubLog.Error(ex, \"DispatchMessage failed\"); }");
        sb.AppendLine("            }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    private sealed class __RegionMsgSub : MyConnection.ISubscribe");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly Action _unsubscribe;");
        sb.AppendLine("        public void UnSubscribe() => _unsubscribe();");
        sb.AppendLine("        public __RegionMsgSub(Action unsubscribe) => _unsubscribe = unsubscribe;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        if (!string.IsNullOrEmpty(info.Namespace))
            sb.AppendLine("}");

        context.AddSource($"{info.ClassName}.UnitMirrorClient.g.cs", sb.ToString());
    }
}
